import { error, IRequest } from "itty-router";
import { getDB, log } from "../../utils.ts";
import {
	ChartMarker,
	chartMarkerStyles,
	chartMarkerTypes,
} from "../../types.ts";

export default async function createMarker(request: IRequest) {
	const data: Partial<ChartMarker> = await request.json();
	console.log(data);

	if (!data.channel) {
		return error(400, "Specify a channel");
	}

	if (!data.value) {
		return error(400, "Specify a value");
	}

	if (!data.label) {
		data.label = "";
	}

	if (!data.colour) {
		data.colour = "black";
	}

	if (typeof data.enabled !== "boolean") {
		data.enabled = true;
	}

	if (!data.style || !chartMarkerStyles.includes(data.style)) {
		data.style = "dashed";
	}

	if (!data.type || !chartMarkerTypes.includes(data.type)) {
		data.type = "fixed-value";
	}

	// Use DB autogenerated ID
	if ("id" in data) {
		delete data.id;
	}

	if (data.type) {
		if (!chartMarkerTypes.includes(data.type)) {
			data.type = "fixed-value";
		}
	}

	// TODO: Also publish to websockets

	const sql = await getDB();

	const id = (
		await sql`INSERT INTO channel_markers ${sql(data)} RETURNING id;`
	)?.[0]?.["id"];
	log.info(`Created marker ${id}`);

	return new Response(id + "", { status: 201 });
}
