name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:   
  build:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v5
  
      - name: Build & Save docker image
        id: build_save
        run: ./save-docker-image.sh ${{ github.ref_name }}.tar
          
          
  
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: Docker image release ${{ github.ref_name }}
          files: ${{ github.ref_name }}.tar
