name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:   
  build:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v5
  
      - name: Build & Save docker image
        id: build_save
        run: |
          file_name=$(grep -oP "(?<=Saved Docker image as ).*" <(./save-docker-image.sh))
          echo "file_name=$file_name" >> $GITHUB_OUTPUT
  
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: Docker image release ${{ github.sha }}
          files: ${{ steps.get_file.outputs.file_name }}
