name: Docker Image CI

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 16 * * FRI' # runs every friday at 4PM

jobs:

  build:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ingest-deno:$(date +%s)
